### ISSUE TITLE
cwltool_launcher as Jtracker adapter to run cwl workflows and tools

### ISSUE THREAD

**Issue by lindaxiang** [ICGC-TCGA-PanCancer/dna-seq-processing#23]
In order to utilize JTracker to execute and orchestrate all existing tools and workflows written in CWL, a Jtracker adapter a.k.a cwltool_launcher which is a generic cli wrapper of the cwltool  is needed. 
The input/output requirements are listed here: https://github.com/ICGC-TCGA-PanCancer/dna-seq-processing/tree/master/cwltool-launcher

**Comment by junjun-zhang** [comment]
addressed by #24
