### ISSUE TITLE
Add another markdup tool: samblaster

### ISSUE THREAD

**Issue by junjun-zhang** [ICGC-TCGA-PanCancer/dna-seq-processing#9]
Github: https://github.com/GregoryFaust/samblaster

Seems to be faster and use less memory: https://academic.oup.com/bioinformatics/article/30/17/2503/2748175. We should test it and compare results with other tools

**Comment by lindaxiang** [comment]
samblaster
* single pass over a SAM file
* always keeps the first such pair found in its input
Although it is not a requirement for duplicate marking software to choose the best pair based on base quality sum. In practice we will move away from using samblaster for this reason.
